title: Jie Ren 任杰
logo: /assets/img/renjie.gif
description: I have taught all my dancing skills to this Koala.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: /README.md
  another_url: another value
